language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="nebo15"
  - MAIN_BRANCHES="master develop"
  - secure: h9VjPv4wW6mZlwis+mpI92GTdxO9iEiUS/3Pc0AVSnApfQBOCh/75aT1MXJ2GF18/vU5YsFZQYDATFRB4vyyNdQKgcPvuu5v9UGu8Hocs8wtoTfiGdYvggFgDdqm8SYZJkkvP1hE407r5tn1mKz+aMhvF32ir7+QFRlEJVlMkdk4XPijq3tl+dDjW9MbeyDY5w1WUNFpZgaAI8/6Rwnh9YetQKAWfCARkqaOzQBQxcrpEUutadea/R6G0CtZSx/CIM+2q38rdoUtnm9GMoflsJxK+6yX9ntiCeXyud8KK43r3Z4ILTMa2sa2tpVr8yUj73MFUocmmAmZ4cwlcrJuoG4QxcP875Klv629jpXWNtdpD1sGwQ0tfktkDdybEYGnXho4rCGhsZcAVvHRQ8cdgnacL7aa1UZ0BZQJkEdvBxEBuDo5A5Ns+dJzrMEC3YL/KUEV9UyKvUPZ+tKvLM1Bdp6jVRNHbl3gGYgy/TXtQOazhf4wTqte0nj4XhDLEOTya1EImmaOhTBFEy4Bl4mORGrpnRu1p+CONCPWX6xP4tDbA+FWiR+bD6Czkap45bLYIlZDV15JFSN+qOkS8vsHOD3RjjJjH38agPuK11PXLjI27WQ2G05ASaFEn+Dk3AibnOORFWp/8M2cbhZe0msSipE24nm7G40hW4KmRAeoxiU=
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- ./bin/version-increment.sh
- ./bin/build.sh
- ./bin/start.sh
- sleep 5
- npm run nightwatch -- -e travis
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`;
- if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is
  not started!" && false; fi;
after_success:
- ./bin/ci/push.sh
