language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="nebo15"
  - MAIN_BRANCHES="master develop"
  - secure: ILfCzXnJC+OZtdhwdOQdyslOa3cf22CJB11H8/HBPTrGeQkabQoxzhZmMksTG1hHj7IaFstPfow15fm4AVVudPC4HIKuK7U9cRx0bfUMDnWs+9X5tSs80f+Sau1eswSEb74f9fDlwBXea+gNbuCIYK8evO7xchRBlttWyNNzMzcW53rswcziYssg10r50VljiQlMuOB0CAv0qvDH9AJpxjnSaiKYLRjBIr+u8fK+MPqEJJEdm0C686qJ6p8pJcAU3dGZVwE8GO6m94QNBSIZcyiBmTJcrO8NshoUdnZx3bWciEhF6ByyXI0oCHhtPvxk6rsGesdkLDuuJ/x3r73Qa/qcWXQ0dJmtQ0uoboTumA8fXUzeGm8HUeeTb4ip8Ut6pAerJtnuHYlUlWFb7NlgJsoY1PMyqUOA3TlGU/ti2cJsy8DdhYydNwI8WSGj+HNMatXzZV5+kL2oamTYgGtqjgplkis2Fc0dTWoTHjpU8GlF++4S3/NFs/ciOcaHhGDWZqi69ibhZn4Qrw+4fqFfeFY+F2EhzEMPeLi5Z8KCuczGnPfCF4tB1Uu2G7zxiGfnfFlp0inNuxqeu8DK/2engmcuRAcEKcYHi4yudMxD3EqWLYdom8CyEQh3BR9DjlnF/kFl5ZyjeEC4wBN8qgrWp/TCX6s5Ji/PbFU7FhOb0i0=
node_js:
- 7.5.0
before_install:
- chmod -R +x bin
script:
- ./bin/version-increment.sh
- ./bin/build.sh
- ./bin/start.sh
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`;
  if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
    echo "[E] Container is not started\!";
    docker logs trump_api --details --since 5h;
    exit 1;
  fi;
after_success:
- ./bin/ci/push.sh
